import { Bell, FileText, LockKey, Medal, ShieldCheck } from "@phosphor-icons/react";
import { route, type RouteGroup } from "../route-config";

export const systemRouteGroup: RouteGroup = {
  moduleName: "system",
  label: "Hệ thống",
  icon: ShieldCheck,
  children: [
    route({
      path: "/system/accounts",
      moduleName: "system.account",
      title: "Tài khoản",
      subtitle: "Account, scope, vai trò chính và trạng thái đăng nhập.",
      endpoint: "/system/accounts",
      idField: "username",
      kind: "accounts",
      icon: ShieldCheck,
      columns: ["username", "primaryRoleName", "deaneryName", "parishName", "status"],
      permissionPrefixes: ["system.account.manage."],
      actionPermissionPrefixes: ["system.account.manage."],
      primaryActionLabel: "Tạo tài khoản",
      filterLabels: ["Vai trò", "Trạng thái"],
      filters: [
        {
          key: "roleCode",
          label: "Vai trò",
          type: "select",
          optionsEndpoint: "/system/roles",
          optionValue: "roleCode",
          optionLabel: "roleName",
        },
        {
          key: "status",
          label: "Trạng thái",
          type: "select",
          options: [
            { value: "all", label: "Tất cả" },
            { value: "active", label: "Đang hoạt động" },
            { value: "inactive", label: "Tạm ngưng" },
          ],
        },
      ],
      workflowHint: "FE không gửi username/password/avatarUrl; backend tự sinh credential.",
    }),
    route({
      path: "/system/roles",
      moduleName: "system.role",
      title: "Vai trò",
      subtitle: "Vai trò nghiệp vụ, mô tả và thứ tự hiển thị.",
      endpoint: "/system/roles",
      idField: "roleCode",
      kind: "roles",
      icon: LockKey,
      columns: ["roleCode", "roleName", "displayOrder", "isSystem", "status"],
      permissionPrefixes: ["system.role.read."],
      actionPermissionPrefixes: ["system.role.create.", "system.role.update.", "system.role.toggle."],
      filters: [
        {
          key: "isSystem",
          label: "Loại vai trò",
          type: "boolean",
          options: [
            { value: "true", label: "Vai trò hệ thống" },
            { value: "false", label: "Vai trò tự tạo" },
          ],
        },
        {
          key: "status",
          label: "Trạng thái",
          type: "select",
          options: [
            { value: "all", label: "Tất cả" },
            { value: "active", label: "Đang hoạt động" },
            { value: "inactive", label: "Tạm ngưng" },
          ],
        },
      ],
      primaryActionLabel: "Thêm vai trò",
      filterLabels: ["Loại vai trò", "Trạng thái"],
    }),
    route({
      path: "/system/permissions",
      moduleName: "system.permission",
      title: "Quyền hạn",
      subtitle: "Permission code do backend sinh từ module/resource/action/scope.",
      endpoint: "/system/permissions",
      idField: "permissionCode",
      kind: "permissions",
      icon: LockKey,
      columns: ["permissionCode", "permissionName", "moduleCode", "resourceCode", "actionCode", "scopeCode", "status"],
      permissionPrefixes: ["system.permission.read.", "system.permission.manage."],
      actionPermissionPrefixes: ["system.permission.update.", "system.permission.toggle."],
      actions: {
        edit: { label: "Sửa", permissionPrefixes: ["system.permission.update."], requiredRoles: ["SUPER_ADMIN", "ROLE_SUPER_ADMIN"] },
      },
      filterLabels: ["Module", "Resource", "Action", "Scope"],
      filters: [
        {
          key: "module.moduleCode",
          label: "Module",
          type: "select",
          optionsEndpoint: "/system/permissions/taxonomy",
          optionCollection: "modules",
          optionValue: "code",
          optionLabel: "name",
        },
        {
          key: "resource.resourceCode",
          label: "Resource",
          type: "select",
          optionsEndpoint: "/system/permissions/taxonomy",
          optionCollection: "resources",
          optionValue: "code",
          optionLabel: "name",
        },
        {
          key: "action.actionCode",
          label: "Action",
          type: "select",
          optionsEndpoint: "/system/permissions/taxonomy",
          optionCollection: "actions",
          optionValue: "code",
          optionLabel: "name",
        },
        {
          key: "scope.scopeCode",
          label: "Scope",
          type: "select",
          optionsEndpoint: "/system/permissions/taxonomy",
          optionCollection: "scopes",
          optionValue: "code",
          optionLabel: "name",
        },
      ],
    }),
    route({
      path: "/system/account-roles",
      moduleName: "system.account-role",
      title: "Gán vai trò",
      subtitle: "Quản lý vai trò tài khoản trong scope hợp lệ.",
      endpoint: "/system/account-roles",
      idField: "id",
      kind: "account-roles",
      icon: ShieldCheck,
      columns: ["username", "roleCode", "isPrimary", "assignedAt", "expiresAt", "status"],
      permissionPrefixes: ["system.account_role.assign."],
      actionPermissionPrefixes: ["system.account_role.assign."],
      primaryActionLabel: "Gán nhiều vai trò",
      filterLabels: ["Vai trò", "Trạng thái", "Hết hạn"],
      filters: [
        {
          key: "role.roleCode",
          label: "Vai trò",
          type: "select",
          optionsEndpoint: "/system/roles",
          optionValue: "roleCode",
          optionLabel: "roleName",
        },
        {
          key: "isPrimary",
          label: "Vai trò chính",
          type: "boolean",
          options: [
            { value: "true", label: "Chính" },
            { value: "false", label: "Phụ" },
          ],
        },
        {
          key: "status",
          label: "Trạng thái",
          type: "select",
          options: [
            { value: "all", label: "Tất cả" },
            { value: "active", label: "Đang hoạt động" },
            { value: "inactive", label: "Tạm ngưng" },
          ],
        },
      ],
    }),
    route({
      path: "/system/role-permissions",
      moduleName: "system.role-permission",
      title: "Phân quyền vai trò",
      subtitle: "Grant hoặc revoke permission cho role được phép quản lý.",
      endpoint: "/system/role-permissions",
      idField: "id",
      kind: "role-permissions",
      icon: LockKey,
      columns: ["roleCode", "permissionCode", "effect", "assignedAt", "expiresAt"],
      permissionPrefixes: ["system.role_permission.read.", "system.role_permission.assign.", "system.role_permission.revoke."],
      actionPermissionPrefixes: ["system.role_permission.assign.", "system.role_permission.revoke."],
      actions: {
        matrix: {
          label: "Cập nhật ma trận",
          permissionPrefixes: ["system.role_permission.assign.", "system.role_permission.revoke."],
          route: "/system/role-permissions/manage/:roleCode",
        },
      },
      primaryActionLabel: "Gán nhiều quyền",
      filterLabels: ["Vai trò", "Module", "Effect"],
      filters: [
        {
          key: "role.roleCode",
          label: "Vai trò",
          type: "select",
          optionsEndpoint: "/system/roles",
          optionValue: "roleCode",
          optionLabel: "roleName",
        },
        {
          key: "effect",
          label: "Hiệu lực",
          type: "select",
          options: ["ALLOW", "DENY"].map((value) => ({ value, label: value })),
        },
      ],
    }),
    route({
      path: "/system/account-permissions",
      moduleName: "system.account-permission",
      title: "Quyền riêng tài khoản",
      subtitle: "ALLOW hoặc DENY trực tiếp theo tài khoản.",
      endpoint: "/system/account-permissions",
      idField: "id",
      kind: "account-permissions",
      icon: Medal,
      columns: ["username", "permissionCode", "effect", "reason", "expiresAt"],
      permissionPrefixes: ["system.account_permission.manage."],
      actionPermissionPrefixes: ["system.account_permission.manage."],
      primaryActionLabel: "Thêm quyền riêng",
      filterLabels: ["Tài khoản", "Effect", "Hết hạn"],
    }),
    route({
      path: "/notifications",
      moduleName: "system.notification",
      title: "Thông báo",
      subtitle: "Inbox workflow và realtime notification theo user hiện tại.",
      endpoint: "/system/notifications",
      idField: "id",
      kind: "notifications",
      icon: Bell,
      columns: ["title", "eventType", "courseCode", "readAt", "createdAt", "status"],
      permissionPrefixes: [],
      filterLabels: ["Tất cả", "Chưa đọc", "Đã đọc"],
    }),
    route({
      path: "/system/audit-logs",
      moduleName: "system.audit-log",
      title: "Nhật ký hệ thống",
      subtitle: "Lịch sử thao tác trong 10 ngày gần nhất.",
      endpoint: "/system/audit-logs",
      idField: "id",
      kind: "audit-logs",
      icon: FileText,
      columns: ["loggedAt", "username", "action", "resourceType", "unitType", "ipAddress"],
      permissionPrefixes: ["system.audit_log.read."],
      filterLabels: ["Người thực hiện", "Module", "Hành động", "Thời gian"],
    }),
  ],
};
