import { ChartBar, ClipboardText } from "@phosphor-icons/react";
import { route, type RouteGroup } from "../route-config";

export const trainingWorkflowRouteGroup: RouteGroup = {
    moduleName: "training-workflow",
    label: "Quy trình huấn luyện",
    icon: ClipboardText,
    children: [
      route({
        path: "/training/registrations",
        createPath: "/training/registrations/new",
        moduleName: "training.registration",
        title: "Đăng ký tham dự",
        subtitle: "Chọn huynh trưởng, kiểm điều kiện và gửi batch đăng ký.",
        endpoint: "/training/participations",
        idField: "id",
        kind: "participations",
        icon: ClipboardText,
        columns: ["leaderFullName", "courseName", "eligible", "exceptionReason", "participationStatus", "status"],
        permissionPrefixes: ["training.participation.read.", "training.participation.submit."],
        actionPermissionPrefixes: ["training.participation.submit."],
        primaryActionLabel: "Gửi đăng ký",
        filterLabels: ["Khóa", "Cấp HT", "Điều kiện"],
        workflowHint: "Batch đăng ký là atomic; hồ sơ không đủ điều kiện phải nhập exception reason.",
      }),
      route({
        path: "/training/approvals",
        moduleName: "training.approval",
        title: "Duyệt đăng ký",
        subtitle: "Duyệt hoặc từ chối hồ sơ theo đúng cấp workflow.",
        endpoint: "/training/participations",
        idField: "id",
        kind: "participations",
        icon: ClipboardText,
        columns: ["leaderFullName", "courseName", "deaneryApprovalStatus", "dioceseApprovalStatus", "review", "status"],
        permissionPrefixes: ["training.participation.approve.", "training.participation.read."],
        actionPermissionPrefixes: ["training.participation.approve."],
        primaryActionLabel: "Duyệt hồ sơ",
        filterLabels: ["Khóa", "Đơn vị gửi", "Trạng thái"],
      }),
      route({
        path: "/training/participations",
        moduleName: "training.participation",
        title: "Danh sách tham dự",
        subtitle: "Theo dõi đăng ký, duyệt, chấm điểm và chứng nhận.",
        endpoint: "/training/participations",
        idField: "id",
        kind: "participations",
        icon: ClipboardText,
        columns: ["leaderFullName", "courseName", "participationStatus", "totalScore", "passed", "certificateApprovalStatus"],
        permissionPrefixes: ["training.participation.read.", "training.participation.approve."],
        actionPermissionPrefixes: ["training.participation.approve.", "training.participation.score."],
        primaryActionLabel: "Xử lý hồ sơ",
        filterLabels: ["Khóa", "Đơn vị gửi", "Trạng thái", "Kết quả"],
        workflowHint: "Score form khóa khi certificateApprovalStatus là APPROVED.",
      }),
      route({
        path: "/training/scores",
        moduleName: "training.score",
        title: "Chấm điểm",
        subtitle: "Nhập điểm theo component của công thức khóa học.",
        endpoint: "/training/participations",
        idField: "id",
        kind: "participations",
        icon: ChartBar,
        columns: ["leaderFullName", "courseName", "scoreFormulaId", "totalScore", "passed", "certificateApprovalStatus"],
        permissionPrefixes: ["training.participation.score.", "training.participation.read."],
        actionPermissionPrefixes: ["training.participation.score."],
        actions: {
          score: {
            label: "Chấm điểm",
            permissionPrefixes: ["training.participation.score."],
            route: "/training/participations/:id/score",
          },
        },
        primaryActionLabel: "Chấm điểm",
        filterLabels: ["Khóa", "Kết quả", "Chứng nhận"],
        workflowHint: "Request score phải gửi đúng và đủ component của formula, không vượt maxScore.",
      }),
    ],
  };
