import { Calculator, ChartBar, GraduationCap, ListChecks } from "@phosphor-icons/react";
import { route, type RouteGroup } from "../route-config";

export const trainingRouteGroup: RouteGroup = {
    moduleName: "training",
    label: "Huấn luyện",
    icon: GraduationCap,
    children: [
      route({
        path: "/training/requirements",
        moduleName: "training.requirement",
        title: "Điều kiện khóa",
        subtitle: "Điều kiện level, tuổi, thâm niên và khóa tiên quyết.",
        endpoint: "/training/requirements",
        idField: "requirementCode",
        kind: "requirements",
        icon: ListChecks,
        columns: ["requirementCode", "requirementName", "courseType", "requiredCurrentLevel", "requiredMinAge", "status"],
        permissionPrefixes: ["training.requirement.read."],
        actionPermissionPrefixes: ["training.requirement.create.", "training.requirement.update.", "training.requirement.toggle."],
        primaryActionLabel: "Thêm điều kiện",
        filterLabels: ["Loại khóa", "Trạng thái"],
      }),
      route({
        path: "/training/courses",
        moduleName: "training.course",
        title: "Khóa huấn luyện",
        subtitle: "Thiết lập khóa, owner scope, thời gian và công thức điểm.",
        endpoint: "/training/courses",
        idField: "courseCode",
        kind: "courses",
        icon: GraduationCap,
        columns: ["courseCode", "courseName", "courseType", "hostYear", "location", "registrationEndAt", "status"],
        permissionPrefixes: ["training.course.read."],
        actionPermissionPrefixes: ["training.course.create.", "training.course.update.", "training.course.toggle."],
        primaryActionLabel: "Tạo khóa",
        filterLabels: ["Năm", "Loại khóa", "Trạng thái", "Thời gian đăng ký"],
        workflowHint: "Mỗi khóa phải có scoreFormulaId cùng owner scope.",
      }),
      route({
        path: "/training/score-components",
        moduleName: "training.score-component",
        title: "Thành phần điểm",
        subtitle: "Biến điểm reusable cho công thức chấm điểm.",
        endpoint: "/training/score-components",
        idField: "code",
        kind: "score-components",
        icon: ChartBar,
        columns: ["code", "name", "maxScore", "unitType", "displayOrder", "status"],
        permissionPrefixes: ["training.score_component.read."],
        actionPermissionPrefixes: ["training.score_component.create.", "training.score_component.update.", "training.score_component.toggle."],
        primaryActionLabel: "Thêm thành phần",
        filterLabels: ["Cấp quản lý", "Trạng thái"],
      }),
      route({
        path: "/training/score-formulas",
        moduleName: "training.score-formula",
        title: "Công thức điểm",
        subtitle: "Công thức, passing score và trạng thái khóa theo dữ liệu chấm.",
        endpoint: "/training/score-formulas",
        idField: "code",
        kind: "score-formulas",
        icon: Calculator,
        columns: ["code", "name", "expression", "passingScore", "locked", "status"],
        permissionPrefixes: ["training.score_formula.read."],
        actionPermissionPrefixes: ["training.score_formula.create.", "training.score_formula.update.", "training.score_formula.toggle."],
        primaryActionLabel: "Tạo công thức",
        filterLabels: ["Cấp quản lý", "Trạng thái khóa"],
        workflowHint: "Formula đã có participation totalScore thì không sửa trực tiếp.",
      }),
    ],
  };
