import { Bell, FileText, LockKey, Medal, ShieldCheck } from "@phosphor-icons/react";
import { route, type RouteGroup } from "../route-config";

export const systemRouteGroup: RouteGroup = {
    moduleName: "system",
    label: "Hệ thống",
    icon: ShieldCheck,
    children: [
      route({
        path: "/system/accounts",
        moduleName: "system.account",
        title: "Tài khoản",
        subtitle: "Account, scope, primary role và trạng thái đăng nhập.",
        endpoint: "/system/accounts",
        kind: "accounts",
        icon: ShieldCheck,
        columns: ["username", "leaderFullName", "primaryRoleCode", "dioceseId", "deaneryId", "parishId", "status"],
        permissionPrefixes: ["system.account.read.", "system.account.manage."],
        actionPermissionPrefixes: ["system.account.create.", "system.account.manage."],
        primaryActionLabel: "Tạo tài khoản",
        filterLabels: ["Vai trò", "Scope", "Trạng thái"],
        workflowHint: "FE không gửi username/password/avatarUrl; backend tự sinh credential.",
      }),
      route({
        path: "/system/roles",
        moduleName: "system.role",
        title: "Vai trò",
        subtitle: "Vai trò nghiệp vụ, mô tả và thứ tự hiển thị.",
        endpoint: "/system/roles",
        kind: "roles",
        icon: LockKey,
        columns: ["roleCode", "roleName", "description", "displayOrder", "status"],
        permissionPrefixes: ["system.role.read.", "system.role.manage."],
        actionPermissionPrefixes: ["system.role.create.", "system.role.manage."],
        primaryActionLabel: "Thêm vai trò",
        filterLabels: ["Trạng thái"],
      }),
      route({
        path: "/system/permissions",
        moduleName: "system.permission",
        title: "Quyền hạn",
        subtitle: "Permission code do backend sinh từ module/resource/action/scope.",
        endpoint: "/system/permissions",
        kind: "permissions",
        icon: LockKey,
        columns: ["permissionCode", "permissionName", "moduleCode", "resourceCode", "actionCode", "scopeCode", "status"],
        permissionPrefixes: ["system.permission.read.", "system.permission.manage."],
        actionPermissionPrefixes: ["system.permission.create.", "system.permission.manage."],
        primaryActionLabel: "Thêm quyền",
        filterLabels: ["Module", "Resource", "Action", "Scope"],
      }),
      route({
        path: "/system/account-roles",
        moduleName: "system.account-role",
        title: "Gán vai trò",
        subtitle: "Quản lý vai trò tài khoản trong scope hợp lệ.",
        endpoint: "/system/account-roles",
        kind: "account-roles",
        icon: ShieldCheck,
        columns: ["username", "roleCode", "isPrimary", "assignedAt", "expiresAt", "status"],
        permissionPrefixes: ["system.account_role.read.", "system.account_role.assign."],
        actionPermissionPrefixes: ["system.account_role.assign."],
        primaryActionLabel: "Gán vai trò",
        filterLabels: ["Vai trò", "Trạng thái", "Hết hạn"],
      }),
      route({
        path: "/system/role-permissions",
        moduleName: "system.role-permission",
        title: "Phân quyền vai trò",
        subtitle: "Grant hoặc revoke permission cho role được phép quản lý.",
        endpoint: "/system/role-permissions",
        kind: "role-permissions",
        icon: LockKey,
        columns: ["roleCode", "permissionCode", "effect", "assignedAt", "expiresAt", "status"],
        permissionPrefixes: ["system.role_permission.read.", "system.role_permission.assign.", "system.role_permission.revoke."],
        actionPermissionPrefixes: ["system.role_permission.assign.", "system.role_permission.revoke."],
        primaryActionLabel: "Cập nhật ma trận",
        filterLabels: ["Vai trò", "Module", "Effect"],
      }),
      route({
        path: "/system/account-permissions",
        moduleName: "system.account-permission",
        title: "Quyền riêng tài khoản",
        subtitle: "ALLOW hoặc DENY trực tiếp theo tài khoản.",
        endpoint: "/system/account-permissions",
        kind: "account-permissions",
        icon: Medal,
        columns: ["username", "permissionCode", "effect", "reason", "expiresAt", "status"],
        permissionPrefixes: ["system.account_permission.read.", "system.account_permission.manage."],
        actionPermissionPrefixes: ["system.account_permission.manage."],
        primaryActionLabel: "Thêm quyền riêng",
        filterLabels: ["Tài khoản", "Effect", "Hết hạn"],
      }),
      route({
        path: "/notifications",
        moduleName: "system.notification",
        title: "Thông báo",
        subtitle: "Inbox workflow và realtime notification theo user hiện tại.",
        endpoint: "/system/notifications",
        kind: "notifications",
        icon: Bell,
        columns: ["title", "eventType", "courseCode", "readAt", "createdAt", "status"],
        permissionPrefixes: [],
        primaryActionLabel: "Đánh dấu đã đọc",
        filterLabels: ["Tất cả", "Chưa đọc", "Đã đọc"],
      }),
      route({
        path: "/system/audit-logs",
        moduleName: "system.audit-log",
        title: "Nhật ký hệ thống",
        subtitle: "Lịch sử thao tác trong 10 ngày gần nhất.",
        endpoint: "/system/audit-logs",
        kind: "audit-logs",
        icon: FileText,
        columns: ["loggedAt", "username", "action", "resourceType", "unitType", "ipAddress"],
        permissionPrefixes: ["system.audit_log.read."],
        filterLabels: ["Người thực hiện", "Module", "Hành động", "Thời gian"],
      }),
    ],
  };
